export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';

export const REFRESH_TOKEN = 'REFRESH_TOKEN';
export const DONE_REFRESHING_TOKEN = 'DONE_REFRESHING_TOKEN';

export const GET_NEWSFEED = 'GET_NEWSFEED';
export const GET_NEWSCARD = 'GET_NEWSCARD';
export const DELETE_NEWSCARD = 'DELETE_NEWSCARD';

export const CHANGE_COLOR = 'CHANGE_COLOR';
export const CLEAR_SETTINGS = 'CLEAR_SETTINGS';

export const STORE_SPOTIFY_INFO = 'STORE_SPOTIFY_INFO';
export const CLEAR_SPOTIFY_INFO = 'CLEAR_SPOTIFY_INFO';
